services:
  backend:
    image: ghcr.io/1294117457/idbackend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    external: true
