"""init base schema

Revision ID: c11f164f0308
Revises: 
Create Date: 2026-07-11 15:44:51.313465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11f164f0308'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('attribute',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('input_min', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('input_max', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('CONDITION', 'TRANSFORM')", name='ck_attribute_type_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attribute_active', 'attribute', ['is_active'], unique=False)
    op.create_index('idx_attribute_group', 'attribute', ['group_code'], unique=False)
    op.create_table('extra_info_field',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extra_info_field_active', 'extra_info_field', ['is_active'], unique=False)
    op.create_index('idx_extra_info_field_sort', 'extra_info_field', ['sort_order', 'id'], unique=False)
    op.create_table('file_metadata',
    sa.Column('object_name', sa.String(length=255), nullable=False, comment='S3 对象 key，如 files/proofs/2025/123/abc.pdf'),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('file_category', sa.Enum('AVATAR', 'PROOF', 'POLICY', name='filecategory', native_enum=False, length=20), nullable=False, comment='决定鉴权分支和 S3 路径前缀'),
    sa.Column('upload_user_id', sa.Integer(), nullable=False, comment='上传用户，部分鉴权场景使用'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('delete_time', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_category_deleted', 'file_metadata', ['file_category', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_file_metadata_file_category'), 'file_metadata', ['file_category'], unique=False)
    op.create_index(op.f('ix_file_metadata_is_deleted'), 'file_metadata', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_file_metadata_object_name'), 'file_metadata', ['object_name'], unique=False)
    op.create_index(op.f('ix_file_metadata_upload_user_id'), 'file_metadata', ['upload_user_id'], unique=False)
    op.create_table('permission',
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('api_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_table('policy_documents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('rule',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('CONDITION', 'TRANSFORM')", name='ck_rule_type_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rule_active', 'rule', ['is_active'], unique=False)
    op.create_index('idx_rule_type', 'rule', ['type'], unique=False)
    op.create_table('system_config',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('template_category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('is_bind_template', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_score >= 0', name='ck_template_category_max_score_nonneg'),
    sa.ForeignKeyConstraint(['parent_id'], ['template_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_category_active', 'template_category', ['is_active'], unique=False)
    op.create_index('idx_template_category_deleted', 'template_category', ['is_deleted'], unique=False)
    op.create_index('idx_template_category_parent_sort', 'template_category', ['parent_id', 'sort_order', 'id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('enrollment_year', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('score_info', sa.JSON(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_attribute',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'attribute_id', name='uk_rule_attribute')
    )
    op.create_index('idx_rule_attribute_attribute', 'rule_attribute', ['attribute_id'], unique=False)
    op.create_index('idx_rule_attribute_rule', 'rule_attribute', ['rule_id'], unique=False)
    op.create_table('template',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_score >= 0', name='ck_template_max_score_nonneg'),
    sa.ForeignKeyConstraint(['category_id'], ['template_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_active', 'template', ['is_active'], unique=False)
    op.create_index('idx_template_category', 'template', ['category_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('apply_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('gain_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['template_category.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_category', 'applications', ['category_id'], unique=False)
    op.create_index('idx_application_status', 'applications', ['status'], unique=False)
    op.create_index('idx_application_user_template_status', 'applications', ['user_id', 'template_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('template_rule',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'rule_id', name='uk_template_rule')
    )
    op.create_index('idx_template_rule_rule', 'template_rule', ['rule_id'], unique=False)
    op.create_index('idx_template_rule_template', 'template_rule', ['template_id'], unique=False)
    op.create_table('application_operation',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operation_app_status', 'application_operation', ['application_id', 'operation'], unique=False)
    op.create_index('idx_operation_application', 'application_operation', ['application_id'], unique=False)
    op.create_table('application_proofs',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('proof_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proofs_application', 'application_proofs', ['application_id'], unique=False)
    op.create_index('idx_proofs_application_status', 'application_proofs', ['application_id', 'status'], unique=False)
    op.create_table('score_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['template_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_data_application', 'score_data', ['application_id'], unique=False)
    op.create_index('idx_score_data_user_active', 'score_data', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_score_data_user_category', 'score_data', ['user_id', 'category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_score_data_user_category', table_name='score_data')
    op.drop_index('idx_score_data_user_active', table_name='score_data')
    op.drop_index('idx_score_data_application', table_name='score_data')
    op.drop_table('score_data')
    op.drop_index('idx_proofs_application_status', table_name='application_proofs')
    op.drop_index('idx_proofs_application', table_name='application_proofs')
    op.drop_table('application_proofs')
    op.drop_index('idx_operation_application', table_name='application_operation')
    op.drop_index('idx_operation_app_status', table_name='application_operation')
    op.drop_table('application_operation')
    op.drop_index('idx_template_rule_template', table_name='template_rule')
    op.drop_index('idx_template_rule_rule', table_name='template_rule')
    op.drop_table('template_rule')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index('idx_application_user_template_status', table_name='applications')
    op.drop_index('idx_application_status', table_name='applications')
    op.drop_index('idx_application_category', table_name='applications')
    op.drop_table('applications')
    op.drop_table('user_role')
    op.drop_index('idx_template_category', table_name='template')
    op.drop_index('idx_template_active', table_name='template')
    op.drop_table('template')
    op.drop_index('idx_rule_attribute_rule', table_name='rule_attribute')
    op.drop_index('idx_rule_attribute_attribute', table_name='rule_attribute')
    op.drop_table('rule_attribute')
    op.drop_table('role_permission')
    op.drop_table('users')
    op.drop_index('idx_template_category_parent_sort', table_name='template_category')
    op.drop_index('idx_template_category_deleted', table_name='template_category')
    op.drop_index('idx_template_category_active', table_name='template_category')
    op.drop_table('template_category')
    op.drop_table('system_config')
    op.drop_index('idx_rule_type', table_name='rule')
    op.drop_index('idx_rule_active', table_name='rule')
    op.drop_table('rule')
    op.drop_table('role')
    op.drop_table('policy_documents')
    op.drop_table('permission')
    op.drop_index(op.f('ix_file_metadata_upload_user_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_object_name'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_is_deleted'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_file_category'), table_name='file_metadata')
    op.drop_index('ix_file_category_deleted', table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_index('idx_extra_info_field_sort', table_name='extra_info_field')
    op.drop_index('idx_extra_info_field_active', table_name='extra_info_field')
    op.drop_table('extra_info_field')
    op.drop_index('idx_attribute_group', table_name='attribute')
    op.drop_index('idx_attribute_active', table_name='attribute')
    op.drop_table('attribute')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
