"""embeddings 表结构同步脚本

直接重建 embeddings 表为 ORM 模型所需结构（无需保留旧数据）。

旧结构（DB dump）→ 新结构（ORM 期望）：
  source_id: 不存在                → varchar(64) + 索引
  chunk_index: 不存在              → integer DEFAULT 0
  embedding: jsonb                 → vector(1024)（pgvector）
  content: text                    → text（保留，加 tsvector 生成列）
  ref_id: 旧业务关联字段           → 移除（不存在于 ORM 模型）
  id: 缺默认值 → GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

若表结构已对但 id 列没默认值（例如上次脚本异常退出），会自动进入
"仅修复 id" 流程，无需手动删表重建。

用法（服务器上）：
  cd /home/dustp/codes/idproject/idbackend
  python3 scripts/migrate_embeddings_schema.py
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from src.infra.config import get_async_database_url


STEPS = [
    # ── 1. DROP 旧表（0 行数据，无需保留）───────────────────────────────
    ("删除旧 embeddings 表（0 行数据）",
     ["DROP TABLE IF EXISTS embeddings CASCADE;"]),

    # ── 2. CREATE 新表（与 ORM 模型一致）───────────────────────────────
    # 注：id 用 GENERATED BY DEFAULT AS IDENTITY，对 asyncpg 兼容性最好，
    #     INSERT 时 DB 自动填值（nextval），不再出现 null id 报错。
    ("重建 embeddings 表（vector 1024 + source_id + chunk_index）",
     ["""
     CREATE TABLE embeddings (
         id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         source_id   character varying(64),
         chunk_index integer                       DEFAULT 0,
         title       character varying(200),
         content     text                          NOT NULL,
         category    character varying(50)        NOT NULL,
         embedding   vector(1024),
         created_at  timestamp with time zone     DEFAULT CURRENT_TIMESTAMP,
         updated_at  timestamp with time zone     DEFAULT CURRENT_TIMESTAMP
     );
     """]),

    # ── 3. 索引 ────────────────────────────────────────────────────────
    ("建 category 索引",
     ["CREATE INDEX ix_embeddings_category ON embeddings (category);"]),
    ("建 source_id 索引",
     ["CREATE INDEX ix_embeddings_source_id ON embeddings (source_id);"]),

    # ── 5. BM25 全文检索（zhparser）────────────────────────────────────
    ("加 content_tsv generated column",
     ["""
     ALTER TABLE embeddings
       ADD COLUMN content_tsv tsvector
       GENERATED ALWAYS AS (
         setweight(to_tsvector('chinese_zh', coalesce(title, '')), 'A') ||
         setweight(to_tsvector('chinese_zh', coalesce(content, '')), 'B')
       ) STORED;
     """]),
    ("建 GIN 全文索引",
     ["CREATE INDEX idx_embeddings_tsv ON embeddings USING GIN (content_tsv);"]),
]


async def main():
    url = get_async_database_url()
    print(f"🔗 连接: {url}")
    print()

    engine = create_async_engine(url, echo=False)

    async with engine.begin() as conn:
        # ── 前置检查
        print("=" * 60)
        print("🔍 前置检查")
        print("=" * 60)

        result = await conn.execute(text("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'embeddings' AND table_schema = 'public'
            ORDER BY ordinal_position;
        """))
        cols = {r.column_name: r.data_type for r in result.fetchall()}

        result = await conn.execute(text(
            "SELECT COUNT(*) FROM embeddings;"
            if 'id' in cols else "SELECT 0;"
        ))
        count = result.scalar_one() if 'id' in cols else 0

        print(f"  当前 embeddings 表：{list(cols.keys())}")
        print(f"  当前数据行数：{count}")

        # 已经是目标结构 → 跳过
        if (
            'source_id' in cols
            and cols.get('embedding') == 'USER-DEFINED'
            and 'chunk_index' in cols
        ):
            # 但 id 列必须有 IDENTITY/默认序列，否则 ORM INSERT 会因 null id 失败
            result = await conn.execute(text("""
                SELECT column_default, is_identity, identity_generation
                FROM information_schema.columns
                WHERE table_name='embeddings' AND column_name='id'
                  AND table_schema='public';
            """))
            row = result.first()
            has_id_default = bool(
                row
                and (
                    row.column_default
                    or (row.is_identity == 'YES'
                        and row.identity_generation in ('BY DEFAULT', 'ALWAYS'))
                )
            )

            if has_id_default:
                print("  ✅ embeddings 已是目标结构（id 有默认值），跳过重建")
                print()
                await _verify(conn)
                await engine.dispose()
                return

            print("  ⚠️  id 列无默认值 → 进入 '仅修复 id' 流程")
            print()
            print("=" * 60)
            print("🔧 修复 id 列（添加 SEQUENCE 默认值）")
            print("=" * 60)
            fix_steps = _id_identity_fix_steps()
            for i, (label, sql) in enumerate(fix_steps, 1):
                if isinstance(sql, (list, tuple)):
                    for s in sql:
                        await conn.execute(text(s))
                else:
                    await conn.execute(text(sql))
                print(f"  [{i:>2}/{len(fix_steps)}] ✅ {label}")
            print()
            await _verify(conn)
            print()
            print("=" * 60)
            print("✅ 完成")
            print("=" * 60)
            await engine.dispose()
            return

        # ── 执行重建
        print()
        print("=" * 60)
        print("📦 重建 embeddings 表")
        print("=" * 60)

        for i, (label, sqls) in enumerate(STEPS, 1):
            if not isinstance(sqls, (list, tuple)):
                sqls = [sqls]
            try:
                for sql in sqls:
                    await conn.execute(text(sql))
                print(f"  [{i:>2}/{len(STEPS)}] ✅ {label}")
            except Exception as e:
                print(f"  [{i:>2}/{len(STEPS)}] ❌ {label}")
                print(f"     → {e}")
                raise

        print()
        print("=" * 60)
        print("🔍 验证")
        print("=" * 60)
        await _verify(conn)

        print()
        print("=" * 60)
        print("✅ 完成")
        print("=" * 60)


def _id_identity_fix_steps():
    """当表结构其余都 OK 但 id 没有默认值时，原地给 id 加 IDENTITY。

    PostgreSQL 不能直接 ALTER COLUMN ... SET IDENTITY，需要：
      1. 建一个 SEQUENCE
      2. 把列默认值设为 nextval(...)
    （asyncpg 多语句不支持，所以拆 2 步）
    """
    return [
        ("建 id 序列",
         "CREATE SEQUENCE IF NOT EXISTS public.embeddings_id_seq "
         "AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;"),
        ("绑定 id 默认值（nextval）",
         "ALTER TABLE public.embeddings "
         "ALTER COLUMN id SET DEFAULT nextval('public.embeddings_id_seq'::regclass);"),
    ]


async def _verify(conn):
    result = await conn.execute(text("""
        SELECT column_name, data_type, is_nullable, is_generated, column_default
        FROM information_schema.columns
        WHERE table_name = 'embeddings' AND table_schema = 'public'
        ORDER BY ordinal_position;
    """))
    rows = list(result.fetchall())

    print(f"\n  📋 embeddings 列结构（共 {len(rows)} 列）：")
    for r in rows:
        flags = []
        if r.is_generated == 'ALWAYS':
            flags.append('GEN')
        if r.column_default:
            flags.append(f"default={r.column_default}")
        flags_s = f"  [{', '.join(flags)}]" if flags else ""
        nullable = "NULL" if r.is_nullable == 'YES' else "NOT NULL"
        print(f"    {r.column_name:<15} {r.data_type:<25} {nullable:<10}{flags_s}")

    result = await conn.execute(text("SELECT COUNT(*) FROM embeddings;"))
    print(f"\n  📊 行数：{result.scalar_one()}")

    result = await conn.execute(text("""
        SELECT indexname FROM pg_indexes
        WHERE tablename = 'embeddings' AND schemaname = 'public'
        ORDER BY indexname;
    """))
    print(f"\n  📇 索引：{[r.indexname for r in result.fetchall()]}")

    result = await conn.execute(text("""
        SELECT extname, extversion FROM pg_extension
        WHERE extname IN ('zhparser', 'vector')
        ORDER BY extname;
    """))
    print(f"  🔌 扩展：{[f'{r.extname}@{r.extversion}' for r in result.fetchall()]}")


if __name__ == "__main__":
    asyncio.run(main())